export const ActionInitType = {
  GET_LIST_ACTIVITY_GROUP : "GET_LIST_ACTIVITY_GROUP",
  DELETE_ACTIVITY_GROUP : "DELETE_ACTIVITY_GROUP",
  ADD_NEW_ACTIVITY_GROUP : "ADD_NEW_ACTIVITY_GROUP",
  GET_DETAIL_LIST_TODO : "GET_DETAIL_LIST_TODO",
  DELETE_DETAIL_LIST_TODO : "DELETE_DETAIL_LIST_TODO",
  CREATE_TODOS : "CREATE_TODOS",
  EDIT_TODOS_DATA : "EDIT_TODOS_DATA",
  CHECKLIST_TODO : "CHECKLIST_TODO",
}